import React, { useState } from 'react';
import { GeneratedSong, PreprocessedData, ModelHyperparameters, TrainingMetric, MidiDatasetItem } from '../types/music';
import { PianoRoll } from './PianoRoll';
import { audioSynth } from '../utils/audioSynth';
import { downloadMidiFile } from '../utils/midiEngine';
import {
  Sparkles,
  Sliders,
  Cpu,
  RefreshCw,
  Download,
  Disc3,
  Layers,
  Terminal,
  Activity,
  FileMusic,
} from 'lucide-react';

interface SunoInspectModalProps {
  song: GeneratedSong | null;
  isOpen: boolean;
  onClose: () => void;
  preprocessedData: PreprocessedData;
  hyperparams: ModelHyperparameters;
  onUpdateHyperparams: (p: Partial<ModelHyperparameters>) => void;
  onOpenPythonScript: () => void;
}

export const SunoInspectModal: React.FC<SunoInspectModalProps> = ({
  song,
  isOpen,
  onClose,
  preprocessedData,
  hyperparams,
  onUpdateHyperparams,
  onOpenPythonScript,
}) => {
  const [activeTab, setActiveTab] = useState<'pianoroll' | 'harmonics' | 'neural' | 'python'>('pianoroll');
  const [analysis, setAnalysis] = useState<any>(null);
  const [isAnalyzing, setIsAnalyzing] = useState(false);

  if (!isOpen || !song) return null;

  const handleAnalyze = async () => {
    setIsAnalyzing(true);
    try {
      const res = await fetch('/api/music/analyze', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          notes: song.notes,
          tempo: song.tempo,
          genre: song.genre,
          modelType: song.model,
        }),
      });
      const data = await res.json();
      setAnalysis(data.analysis || data.fallback);
    } catch {
      setAnalysis({
        detectedKey: song.keySignature || 'D Minor',
        harmonicProgression: 'Cadential progression with modal fifth substitutions',
        melodicContour: 'Syncopated wave contour with motif preservation',
        tonalCoherence: 'High',
        aestheticStyle: `${song.genre} generative piece`,
        theoryCritique: 'Clean motivic repetition with natural resolution points.',
        recommendation: 'Adjust temperature or try Bi-LSTM for more polyphonic chord voice-leading.',
      });
    } finally {
      setIsAnalyzing(false);
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-950/85 backdrop-blur-md">
      <div className="bg-slate-900 border border-slate-800 rounded-2xl w-full max-w-4xl max-h-[90vh] flex flex-col shadow-2xl overflow-hidden">
        {/* Header */}
        <div className="p-5 border-b border-slate-800 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-purple-500/10 border border-purple-500/30 flex items-center justify-center text-purple-400">
              <Cpu className="w-5 h-5" />
            </div>
            <div>
              <h3 className="text-base font-bold text-white">Neural Music Engine Inspector</h3>
              <p className="text-xs text-slate-400">
                Inspect note sequences, piano roll, harmonic voice leading, and deep learning hyperparameters for <span className="text-white font-medium">"{song.title}"</span>
              </p>
            </div>
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={onClose}
              className="px-3 py-1.5 text-xs font-semibold bg-slate-800 hover:bg-slate-700 text-slate-200 rounded-lg transition-colors"
            >
              Close
            </button>
          </div>
        </div>

        {/* Tab navigation */}
        <div className="px-6 border-b border-slate-800 bg-slate-950/40 flex items-center gap-2 pt-3">
          {[
            { id: 'pianoroll', label: 'Piano Roll & Notes' },
            { id: 'harmonics', label: 'Harmonic & Music Theory Analysis' },
            { id: 'neural', label: 'LSTM / GAN Architecture' },
          ].map((t) => (
            <button
              key={t.id}
              onClick={() => setActiveTab(t.id as any)}
              className={`px-4 py-2 text-xs font-medium border-b-2 transition-colors -mb-px ${
                activeTab === t.id
                  ? 'border-sky-400 text-sky-400 font-semibold'
                  : 'border-transparent text-slate-400 hover:text-slate-200'
              }`}
            >
              {t.label}
            </button>
          ))}
        </div>

        {/* Tab content */}
        <div className="flex-1 overflow-y-auto p-6 space-y-6">
          {activeTab === 'pianoroll' && (
            <div className="space-y-4">
              <div className="flex items-center justify-between text-xs text-slate-400 font-mono">
                <span>{song.notes.length} notes generated by {song.model}</span>
                <span>Tempo: {song.tempo} BPM · Key: {song.keySignature}</span>
              </div>

              <PianoRoll
                notes={song.notes}
                totalDuration={song.duration}
                height={260}
                instrument={song.instrument}
              />

              <div className="flex items-center justify-between pt-2">
                <span className="text-xs text-slate-400">Audition notes by clicking the piano keys on the left.</span>
                <div className="flex gap-2">
                  <button
                    onClick={() => downloadMidiFile(song.notes, song.tempo, `${song.title}.mid`)}
                    className="px-3 py-1.5 text-xs font-medium bg-slate-800 hover:bg-slate-700 text-slate-200 rounded-md transition-colors flex items-center gap-1.5"
                  >
                    <Download className="w-3.5 h-3.5" />
                    <span>Download MIDI</span>
                  </button>
                  <button
                    onClick={() => audioSynth.downloadWavFile(song.notes, song.instrument, `${song.title}.wav`)}
                    className="px-3 py-1.5 text-xs font-semibold bg-sky-400 hover:bg-sky-300 text-slate-950 rounded-md transition-colors flex items-center gap-1.5"
                  >
                    <Disc3 className="w-3.5 h-3.5" />
                    <span>Download WAV</span>
                  </button>
                </div>
              </div>
            </div>
          )}

          {activeTab === 'harmonics' && (
            <div className="space-y-4">
              <div className="flex items-center justify-between">
                <div>
                  <h4 className="text-sm font-semibold text-white">Gemini Musicological Theory Engine</h4>
                  <p className="text-xs text-slate-400">Deconstructs key centers, cadence closures, and harmonic tensions</p>
                </div>

                <button
                  onClick={handleAnalyze}
                  disabled={isAnalyzing}
                  className="px-3 py-1.5 text-xs font-medium bg-sky-500 hover:bg-sky-400 text-slate-950 rounded-lg transition-colors flex items-center gap-1.5 font-semibold"
                >
                  <RefreshCw className={`w-3.5 h-3.5 ${isAnalyzing ? 'animate-spin' : ''}`} />
                  <span>{isAnalyzing ? 'Analyzing...' : 'Run Musicology Critique'}</span>
                </button>
              </div>

              {analysis ? (
                <div className="bg-slate-950 p-5 rounded-xl border border-slate-800 space-y-4 text-xs">
                  <div className="grid grid-cols-2 md:grid-cols-3 gap-3">
                    <div className="p-3 bg-slate-900/60 rounded-lg border border-slate-800">
                      <span className="text-slate-500 block text-[11px]">Tonality</span>
                      <span className="font-semibold text-sky-400 text-sm">{analysis.detectedKey}</span>
                    </div>
                    <div className="p-3 bg-slate-900/60 rounded-lg border border-slate-800">
                      <span className="text-slate-500 block text-[11px]">Melodic Contour</span>
                      <span className="font-semibold text-emerald-400 text-sm">{analysis.melodicContour}</span>
                    </div>
                    <div className="p-3 bg-slate-900/60 rounded-lg border border-slate-800">
                      <span className="text-slate-500 block text-[11px]">Aesthetic Style</span>
                      <span className="font-semibold text-purple-400 text-sm">{analysis.aestheticStyle}</span>
                    </div>
                  </div>

                  <div className="space-y-2">
                    <span className="font-semibold text-slate-300 block">Harmonic Structure:</span>
                    <p className="text-slate-400 leading-relaxed">{analysis.harmonicProgression}</p>
                  </div>

                  <div className="p-3 bg-slate-900/80 rounded-lg border border-slate-800/80 text-slate-300 italic">
                    "{analysis.theoryCritique}"
                  </div>

                  <div className="p-3 bg-sky-950/20 border border-sky-900/40 rounded-lg text-sky-300">
                    <span className="font-semibold mr-2">Recommendation:</span>
                    {analysis.recommendation}
                  </div>
                </div>
              ) : (
                <div className="p-10 text-center text-slate-500 text-xs border border-dashed border-slate-800 rounded-xl">
                  Click "Run Musicology Critique" to run AI harmonic analysis on this track.
                </div>
              )}
            </div>
          )}

          {activeTab === 'neural' && (
            <div className="space-y-5">
              <div className="bg-slate-950 p-4 rounded-xl border border-slate-800 space-y-3 font-mono text-xs">
                <div className="flex justify-between items-center text-slate-300">
                  <span>Architecture</span>
                  <span className="text-sky-400 font-bold">{song.model}</span>
                </div>
                <div className="flex justify-between items-center text-slate-300">
                  <span>Vocabulary Size</span>
                  <span className="text-slate-400">{preprocessedData.vocabulary.length} distinct musical tokens</span>
                </div>
                <div className="flex justify-between items-center text-slate-300">
                  <span>Sequence Context Window</span>
                  <span className="text-slate-400">{hyperparams.sequenceLength} notes</span>
                </div>
                <div className="flex justify-between items-center text-slate-300">
                  <span>Hidden Dimensions</span>
                  <span className="text-slate-400">{hyperparams.hiddenUnits} recurrent units</span>
                </div>
              </div>

              <div className="flex justify-end">
                <button
                  onClick={onOpenPythonScript}
                  className="px-4 py-2 text-xs font-semibold bg-slate-800 hover:bg-slate-700 text-sky-300 border border-slate-700 rounded-lg transition-colors flex items-center gap-1.5"
                >
                  <Terminal className="w-4 h-4 text-sky-400" />
                  <span>View & Export music21 / PyTorch Code</span>
                </button>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};
